before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - binary: terrap
    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    flags:
      - -mod=vendor

    env:
        - CGO_ENABLED=0

    ldflags:
        - -X "github.com/sirrend/terrap-cli/internal/version.Version={{.Tag}}"

release:
    prerelease: auto
    mode: replace
    github:
        owner: sirrend
        name: terrap-cli

universal_binaries:
  - id: terrap
    replace: true

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - name: terrap
    homepage: "https://github.com/sirrend/terrap-cli.git"
    description: "CLI utility for finding any change between Terraform schemas"
    license: "Apache2.0"
    tap:
        name: homebrew-sirrend
        owner: sirrend
        branch: main
    commit_author:
      name: TerrapCI
      email: terrapci@sirrend.com

checksum:
  name_template: 'checksums.txt'